"""Explicit plugin allowlist.

Keeping the list explicit prevents an unexpected Python file dropped into the
plugins directory from being imported automatically at startup.
"""

ALL_MODULES = [
    ".admins.auth",
    ".admins.callback",
    ".admins.loop",
    ".admins.mute",
    ".admins.pause",
    ".admins.resume",
    ".admins.seek",
    ".admins.shuffle",
    ".admins.skip",
    ".admins.stop",
    ".admins.unmute",
    ".bot.help",
    ".bot.inline",
    ".bot.settings",
    ".bot.start",
    ".misc.autoleave",
    ".misc.seeker",
    ".misc.suggestion",
    ".modules.botwelcomlog",
    ".modules.broadcast",
    ".modules.id",
    ".modules.punishment",
    ".play.channel",
    ".play.group_picker",
    ".play.live",
    ".play.play",
    ".play.playlist",
    ".play.playmode",
    ".play.private",
    ".play.stream",
    ".play.toptracks",
    ".sudo.autoend",
    ".sudo.blacklistchat",
    ".sudo.block",
    ".sudo.dev",
    ".sudo.logger",
    ".sudo.maintenance",
    ".sudo.private",
    ".sudo.sudoers",
    ".sudo.videolimit",
    ".sudo.videomode",
    ".tools.active",
    ".tools.languages",
    ".tools.lyrics",
    ".tools.ping",
    ".tools.queue",
    ".tools.reload",
    ".tools.songs",
    ".tools.speedtest",
    ".tools.stats",
]

__all__ = ["ALL_MODULES"]
